### PR TITLE
Resolve #1

### LINKED ISSUE #1: Resolver l1q01.py
Assine ou comente esta issue se você deseja solucionar a questão [l1q01.py](https://github.com/matheusvictor/Pydawan/blob/master/lista01/l1q01.py).

### PR DESCRIPTION
**Pull request by sameer-j**
Resolves #1
Please review and let me know.

### CODE REVIEW

**Review by matheusvictor — CHANGES_REQUESTED** [review]
Do you can write comments on english to? Or, if you prefer, this lesson can be resolved in this path, on the same way that you have resolved before: [list01 (en)](https://github.com/matheusvictor/Pydawan/tree/master/list01_en) :D
There the problems statements need translations too. Thanks for your support!

**Comment by sameer-j** [comment]
By mistake the repo got deleted. I will give another pull request for this after #23 is merged.

**Comment by matheusvictor** [comment]
@sameer-j : I closed #23 few minutes ago. If you wish resolve the question `l1q01.py`, please, do it on [list01_en](https://github.com/matheusvictor/Pydawan/tree/master/list01_en) or do it with pt-BR words/comments on [lista01_pt-BR](https://github.com/matheusvictor/Pydawan/tree/master/lista01_pt-BR). Ok?!
Thanks for your comprehension! :smile:

**Comment by matheusvictor** [comment]
@sameer-j : I labeled "Resolve #1" PR as `invalid`, ok? Thanks for your contributions ;D

**Pull request closed without merging**
