### PR TITLE
Resolver l1q05.py #28

### PR DESCRIPTION
**Pull request by iamlalith**
#28 @matheusvictor Added Fahrenheit to Celsius converter

### CODE REVIEW

**Comment by iamlalith** [comment]
Wondering if i can also add Celsius to Fahrenheit converter to this and not just Fahrenheit to  Celsius alone?

**Comment by matheusvictor** [comment]
@iamlalith : There is another issue with this problem. Check question [list01_en/l1q04.py](https://github.com/matheusvictor/Pydawan/blob/master/list01_en/l1q04.py)

**Review by matheusvictor — CHANGES_REQUESTED** [review]
@iamlalith : How much would be 14.5 ºF in ºC? Or ºF are just absolute values?

**Comment by iamlalith** [comment]
@matheusvictor Solved both l1q05 and l1qo4.
Sorry for the inconvenience PR for both the files was done in a single PR instead of separate PR's

**Review by matheusvictor — APPROVED** [review]

**Pull request merged**
